### ISSUE TITLE
Add the ability to goto an RA directly from within Sherlock

### ISSUE THREAD

**Issue by vastator69** [MarkIannucci/ChromeUserWebSearchExtension#28]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to use this to lookup RA's directly by their number

**Describe the solution you'd like**
For example:  uw sherlock ra XXXX
where XXXX is the ra#

**Describe alternatives you've considered**
For example:  uw sherlockRA XXXX
From what I saw of the code, this might be easier?

**Comment by MarkIannucci** [comment]
@vastator69, I like the suggestion, and your proposed alternative.  Epic's customer facing RA #'s are different from the RA ID which is what is used in the direct url to a RA, so the best option I have found thus far is to take you to a RA search.  

I have noticed that if you punch in a customer facing RA # directly into their search box when you're already on a different RA it takes you directly to the one you want, but it looks like to take advantage of that functionality the user would have to be authenticated and we'd have to talk to Epic's undocumented RA API to determine the ID...  The dependency on someone already being authenticated and then impersonating them in order to make calls to an undocumented API is not a step that I want to take with this code.

So, I'm going to add functionality to offer RA searching via uw ra.  

If you can figure out a way to derive the url of a RA, please pipe up and I'll implement (or you can take a shot with a pull request)

**Comment by MarkIannucci** [comment]
@vastator69 , I sent the Sherlock Support people an e-mail asking if they can expose a customer facing RA # URL endpoint for us.  If they do, I'll gladly refactor the implementation so RA#'s go straight to the RA skipping the search screen.
